-- MySQL Script generated by MySQL Workbench
-- Wed Mar 27 10:13:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- This is DB for testing
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
--
-- This is DB for testing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `customer_id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `customer_group` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`customer_id`));

CREATE INDEX `PK_Index` ON `mydb`.`customer` (`customer_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `customerid` BIGINT(10) NOT NULL,
  `address_type` CHAR(10) NOT NULL,
  `address_details` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`address_id`, `customerid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `account_id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `customer_id` BIGINT(10) NOT NULL,
  `account_status` CHAR(1) NOT NULL,
  `account_opendate` DATE NOT NULL,
  `account_limit` BIGINT(18) NOT NULL,
  `account_orginalLimit` BIGINT(18) NULL,
  `account_balance` BIGINT(18) NOT NULL,
  `account_duedate` DATE NOT NULL,
  `account_overdue` CHAR(1) NOT NULL,
  `account_firstODdate` DATE NOT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB;

CREATE INDEX `index_account_id` ON `mydb`.`account` (`account_id` ASC) ;


-- -----------------------------------------------------
-- Table `mydb`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedule` (
  `schedule_id` TINYINT(2) NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT(10) NOT NULL,
  `schedule_startDate` DATE NOT NULL,
  `schedule_nextInstalDueDate` DATE NOT NULL,
  `schedule_lastDueDate` DATE NOT NULL,
  `schedule_scheme` CHAR(3) NOT NULL,
  `schedule_intRate` DOUBLE NOT NULL,
  `schedule_instalmentAmount` BIGINT(18) NOT NULL,
  `schedule_modifytimestamp` DATETIME(6) NOT NULL,
  PRIMARY KEY (`schedule_id`, `account_id`),
  CONSTRAINT `fk_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_account_id_idx` ON `mydb`.`schedule` (`account_id` ASC) ;


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `transaction_id` BIGINT(20) NOT NULL,
  `account_id` BIGINT(10) NOT NULL,
  `transaction_date` DATE NOT NULL,
  `transaction_type` CHAR(3) NOT NULL,
  `transaction_amount` BIGINT(18) NOT NULL,
  `transaction_interest` BIGINT(18) NOT NULL,
  `transaction_assoicateAcount` BIGINT(10) NOT NULL,
  `transaction_accountBalBefore` BIGINT(18) NOT NULL,
  PRIMARY KEY (`transaction_id`),
  CONSTRAINT `fk_accountid`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_accountid_idx` ON `mydb`.`transaction` (`account_id` ASC) ;


-- -----------------------------------------------------
-- Table `mydb`.`repaymenthistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`repaymenthistory` (
  `account_id` BIGINT(10) NOT NULL,
  `instal_duedate` DATE NOT NULL,
  `overdue_staus` CHAR(1) NOT NULL,
  `instal_amount` BIGINT(18) NOT NULL,
  `instal_paid` BIGINT(18) NOT NULL,
  `instal_principalportion` BIGINT(18) NOT NULL,
  `instal_interestportion` BIGINT(18) NOT NULL,
  `instal_principal_paid` BIGINT(18) NOT NULL,
  `instal_paiddate` DATE NOT NULL,
  PRIMARY KEY (`account_id`, `instal_duedate`),
  CONSTRAINT `fk2_accountId`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `index_status` ON `mydb`.`repaymenthistory` (`overdue_staus` ASC) ;

CREATE INDEX `index_paymentdate` ON `mydb`.`repaymenthistory` (`instal_paiddate` ASC) ;

CREATE INDEX `index_accountid` ON `mydb`.`repaymenthistory` (`account_id` ASC) ;


-- -----------------------------------------------------
-- Table `mydb`.`interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`interest` (
  `account_id` BIGINT(10) NOT NULL,
  `int_enddate` DATE NOT NULL,
  `int_lastCalDate` DATE NOT NULL,
  `int_balanceBase` BIGINT(18) NOT NULL,
  `int_rate` DOUBLE NOT NULL,
  `int_accrued` BIGINT(18) NOT NULL,
  `int_collected` BIGINT(18) NOT NULL,
  `int_odIntAccrued` BIGINT(18) NOT NULL,
  `int_odIntCollected` BIGINT(18) NOT NULL,
  `int_odrate` DOUBLE NOT NULL,
  `int_modifyTimeStamp` DATETIME(6) NOT NULL,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `fk3_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
